### ISSUE TITLE
setup getSelectedTask process IMPORTANT

### ISSUE THREAD

**Issue by rbrtbrnschn** [rbrtbrnschn/mr-taskman#67]
This is crucial to setup other commands like:
task description | editing the description of selected Task
task complete | setting task.complete to true changing color on embed
task deadline | set deadline chang embed accordingly
task add / remove participant | self explanatory

**Comment by rbrtbrnschn** [comment]
@carlank I do not like simply assinging this to you, but I know you able to solve the current issues regarding the typing of our guildInterface/populatedGuildInterface.
Lmk if you do not want to do this. It's fine too.

**Comment by carlank** [comment]
> @carlank I do not like simply assinging this to you, but I know you able to solve the current issues regarding the typing of our guildInterface/populatedGuildInterface.
> Lmk if you do not want to do this. It's fine too.

Assigning stuff to me is a great way to get it onto my radar, feel free to! If I don't want to take it on, I'll unassign it and comment

**Comment by rbrtbrnschn** [comment]
will keep that in mind!
good work on this man.
